---
abstract: 'search the internet from your terminal'
author:
  - 'Ahmad Syaltut <Isyaltut@gmail.com>'
build_requires:
  FindBin: 0
  Test::More: 0
  Test::Output: 0
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-lookup
requires:
  Browser::Open: 0
  Config::Tiny: 0
  File::Basename: 0
  File::Spec: 0
  Getopt::Long: 0
  IPC::System::Simple: 0
  List::Util: 0
  Pod::Usage: 0
  Text::Abbrev: 0
  Text::Wrap: 0
  URI::Encode: 0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/Syaltut/perl-App-lookup
  repository: git://github.com/Syaltut/perl-App-lookup.git
version: 0.03
